"""create aircraft and tasks tables

Revision ID: 559641e027ee
Revises: 
Create Date: 2023-08-28 01:54:25.290829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559641e027ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ata_chapter_number', sa.Integer(), nullable=True),
    sa.Column('ata_chapter_name', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Maintenance_tasks')
    op.drop_table('Aircraft')
    # ### end Alembic commands ###
