"""create Aircraft and Aircraft tasks tables

Revision ID: 09a3ee2ace97
Revises: 
Create Date: 2023-08-28 20:46:02.154311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a3ee2ace97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ata_chapter_number', sa.Integer(), nullable=True),
    sa.Column('ata_chapter_name', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['Aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Maintenance_tasks')
    op.drop_table('Aircraft')
    # ### end Alembic commands ###
